-- 4_interrogation.sql
USE luxury_fashion_db;

-- Let's see what kinds of boutique prestige tiers we currently have in our network
SELECT DISTINCT Prestige_Tier 
FROM BOUTIQUE;

-- We need a list of clients who speak English or French to send out localized invitations for the Paris show
SELECT First_Name, Last_Name, Email, Preferred_Language 
FROM CLIENT_VIP 
WHERE Preferred_Language IN ('English', 'French');

-- Let's look at bespoke orders placed between 2023 and 2024 to understand our recent custom revenue, sorted by the highest price
SELECT VIP_Number, Order_Date, Final_Price, Production_Status 
FROM BESPOKE_ORDER 
WHERE Order_Date BETWEEN '2023-01-01' AND '2024-12-31' 
ORDER BY Final_Price DESC;

-- Find all products made with crocodile leather so we can feature them in our upcoming exotic materials campaign
SELECT Product_Name, Catalog_Price, Material_Description 
FROM LIMITED_PRODUCT 
WHERE Material_Description LIKE '%Crocodile%';

-- Let's pull up all bespoke orders over 50,000 euros to identify our biggest single-item spenders
SELECT VIP_Number, Order_Date, Final_Price 
FROM BESPOKE_ORDER 
WHERE Final_Price > 50000 
ORDER BY Final_Price DESC;


-- How many bespoke orders are currently sitting in each stage of production?
SELECT Production_Status, COUNT(*) AS Total_Orders 
FROM BESPOKE_ORDER 
GROUP BY Production_Status;

-- What is the average price of our limited edition products per category? This helps with pricing strategy
SELECT Product_Category, AVG(Catalog_Price) AS Average_Price 
FROM LIMITED_PRODUCT 
GROUP BY Product_Category;

-- Get the highest and lowest catalog prices for each product category 
SELECT Product_Category, MAX(Catalog_Price) AS Highest_Price, MIN(Catalog_Price) AS Lowest_Price 
FROM LIMITED_PRODUCT 
GROUP BY Product_Category;

-- Find our most active clients who have purchased more than 2 limited edition items overall
SELECT VIP_Number, SUM(Purchase_Quantity) AS Total_Items_Bought 
FROM PURCHASE 
GROUP BY VIP_Number 
HAVING SUM(Purchase_Quantity) > 2;

-- Calculate the total bespoke revenue generated by each boutique, but only show the ones that made over 100,000 euros
SELECT Boutique_Code, SUM(Final_Price) AS Total_Bespoke_Revenue 
FROM BESPOKE_ORDER 
GROUP BY Boutique_Code 
HAVING SUM(Final_Price) > 100000;


-- Match clients with their bespoke orders so we know exactly who is buying what custom pieces
SELECT c.First_Name, c.Last_Name, b.Order_Date, b.Final_Price 
FROM CLIENT_VIP c 
INNER JOIN BESPOKE_ORDER b ON c.VIP_Number = b.VIP_Number;

-- Pull a full purchase history showing the client's name, what limited product they bought, and when
SELECT c.Last_Name, p.Product_Name, pu.Purchase_Date, pu.Purchase_Quantity 
FROM PURCHASE pu
INNER JOIN CLIENT_VIP c ON pu.VIP_Number = c.VIP_Number
INNER JOIN LIMITED_PRODUCT p ON pu.Product_Reference = p.Product_Reference;

-- Find out which specific boutiques currently have handbags in stock for VIPs who want to make an immediate purchase
SELECT b.Boutique_Name, b.Boutique_City, p.Product_Name, s.Stock_Quantity 
FROM BOUTIQUE b
INNER JOIN STOCK s ON b.Boutique_Code = s.Boutique_Code
INNER JOIN LIMITED_PRODUCT p ON s.Product_Reference = p.Product_Reference
WHERE p.Product_Category = 'Handbag';

-- Show all limited products and their stock levels across all boutiques, including items that currently have zero stock
SELECT p.Product_Name, s.Boutique_Code, s.Stock_Quantity 
FROM LIMITED_PRODUCT p 
LEFT JOIN STOCK s ON p.Product_Reference = s.Product_Reference;

-- Let's see the total quantity of limited products purchased by each client tier to see which tier drives the most volume
SELECT c.Spend_Tier, SUM(pu.Purchase_Quantity) AS Total_Bought 
FROM CLIENT_VIP c 
INNER JOIN PURCHASE pu ON c.VIP_Number = pu.VIP_Number 
GROUP BY c.Spend_Tier;


-- Find VIP clients who have never placed a custom bespoke order, so we can target them with a special introductory offer
SELECT First_Name, Last_Name, Spend_Tier 
FROM CLIENT_VIP 
WHERE VIP_Number NOT IN (
    SELECT VIP_Number FROM BESPOKE_ORDER
);

-- Identify boutiques that currently have at least one bespoke order in the 'Materials Sourced' phase
SELECT Boutique_Name, Boutique_City 
FROM BOUTIQUE b 
WHERE EXISTS (
    SELECT 1 FROM BESPOKE_ORDER o 
    WHERE b.Boutique_Code = o.Boutique_Code AND o.Production_Status = 'Materials Sourced'
);

-- What is the absolute most expensive limited edition product we sell?
SELECT Product_Name, Product_Category, Catalog_Price 
FROM LIMITED_PRODUCT 
WHERE Catalog_Price >= ALL (
    SELECT Catalog_Price FROM LIMITED_PRODUCT
);

-- Get the names of the boutiques that have at least one watch in their current stock
SELECT Boutique_Name, Boutique_City 
FROM BOUTIQUE 
WHERE Boutique_Code = ANY (
    SELECT s.Boutique_Code 
    FROM STOCK s 
    INNER JOIN LIMITED_PRODUCT p ON s.Product_Reference = p.Product_Reference 
    WHERE p.Product_Category = 'Watch'
);

-- Find the names of our top Diamond tier clients who have bought a limited product worth more than 10,000 euros
SELECT First_Name, Last_Name 
FROM CLIENT_VIP 
WHERE Spend_Tier = 'Diamond' 
AND VIP_Number IN (
    SELECT pu.VIP_Number 
    FROM PURCHASE pu 
    INNER JOIN LIMITED_PRODUCT p ON pu.Product_Reference = p.Product_Reference 
    WHERE p.Catalog_Price > 10000
);